# /etc/turnserver.conf
listening-port=3478
tls-listening-port=5349
alt-listening-port=3480
alt-tls-listening-port=5351

# Interface rules
listening-ip=0.0.0.0

# Transport protocols
udp-self-balance
tcp-self-balance

# Domain credentials settings
realm=live.akhu.uz
userdb=/var/lib/coturn/turnuserdb.db

# Long-term credentials mechanism
lt-cred-mech

# TLS settings for encrypted TURN connection
cert=/etc/letsencrypt/live/live.akhu.uz/fullchain.pem
pkey=/etc/letsencrypt/live/live.akhu.uz/privkey.pem
tls-headers-cipher-list="ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"

# Security controls
no-multicast-peers
no-stdout-log
log-file=/var/log/turnserver.log
simple-log

# Keepalive and allocations lifetime limits
allocation-lifetime=3600
stale-nonce=600
