# Generated by Django 5.2.16 on 2026-07-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Camera Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rtsp_url', models.CharField(max_length=500, verbose_name='RTSP URL')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('port', models.PositiveIntegerField(default=554, verbose_name='Port')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Password')),
                ('building', models.CharField(max_length=100, verbose_name='Building')),
                ('floor', models.CharField(max_length=50, verbose_name='Floor')),
                ('room', models.CharField(max_length=50, verbose_name='Room')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Status')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='regions.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['region', 'building', 'room', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CameraStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], max_length=20, verbose_name='Status')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Response Time (ms)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Checked At')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_checks', to='cameras.camera', verbose_name='Camera')),
            ],
            options={
                'verbose_name': 'Camera Status',
                'verbose_name_plural': 'Camera Statuses',
                'ordering': ['-checked_at'],
            },
        ),
    ]
