from rest_framework import viewsets, permissions, status
from rest_framework.views import APIView
from rest_framework.response import Response
from django.utils import timezone
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from screens.models import Computer, ScreenSession, ScreenSnapshot, Heartbeat, AgentToken
from screens.serializers import ComputerSerializer, ScreenSnapshotSerializer
from logs.models import ActivityLog

# Helper to authenticate screen agent requests
def get_authenticated_agent(request):
    auth_header = request.headers.get('Authorization', '')
    if auth_header.startswith('Token '):
        token_key = auth_header[6:].strip()
        try:
            token = AgentToken.objects.select_related('computer__region').get(token=token_key)
            return token.computer
        except AgentToken.DoesNotExist:
            logger.warning(f"AgentToken authentication failed: Token '{token_key}' does not exist.")
    return None


class AgentRegisterAPIView(APIView):
    """
    POST /api/screens/register/
    Verifies agent_id and agent_secret_key generated by Region Admin,
    registers initial hardware properties, and issues an authentication Token.
    """
    permission_classes = [permissions.AllowAny]

    def post(self, request):
        agent_id = request.data.get('agent_id')
        agent_secret_key = request.data.get('agent_secret_key')
        
        if not agent_id or not agent_secret_key:
            return Response(
                {'detail': _('Credentials agent_id and agent_secret_key are required.')},
                status=status.HTTP_400_BAD_REQUEST
            )
            
        try:
            computer = Computer.objects.get(agent_id=agent_id, agent_secret_key=agent_secret_key)
        except (Computer.DoesNotExist, ValueError, TypeError):
            return Response(
                {'detail': _('Authentication failed. Invalid agent ID or secret key.')},
                status=status.HTTP_401_UNAUTHORIZED
            )
            
        # Update computer with initial registration details
        computer.hostname = request.data.get('hostname', '')
        computer.mac_address = request.data.get('mac_address', '')
        computer.username = request.data.get('username', '')
        computer.os_version = request.data.get('os_version', '')
        computer.status = Computer.Statuses.ONLINE
        computer.last_seen = timezone.now()
        computer.save()

        # Issue/get authorization token
        token, created = AgentToken.objects.get_or_create(computer=computer)
        
        # Log registration
        ActivityLog.objects.create(
            user=None,
            action='agent_registered',
            description=f"Screen Agent on computer '{computer.name}' (Asset: {computer.asset_number}) successfully registered.",
            ip_address=request.META.get('REMOTE_ADDR')
        )
        
        return Response({
            'status': 'success',
            'token': token.token,
            'computer_id': computer.id,
            'computer_name': computer.name,
            'stream_name': f"screen_{computer.id}",
            'region_name': computer.region.name
        })


class AgentHeartbeatAPIView(APIView):
    """
    POST /api/screens/heartbeat/
    Receives current resource loads and stream metrics from active agents.
    """
    permission_classes = [permissions.AllowAny]

    def post(self, request):
        computer = get_authenticated_agent(request)
        if not computer:
            return Response({'detail': _('Invalid agent token.')}, status=status.HTTP_401_UNAUTHORIZED)
            
        # Extract metrics
        cpu = float(request.data.get('cpu_usage', 0.0))
        ram = float(request.data.get('ram_usage', 0.0))
        disk = float(request.data.get('disk_usage', 0.0))
        net_speed = float(request.data.get('network_speed', 0.0))
        uptime = float(request.data.get('uptime', 0.0))
        
        # Cache FFmpeg command and logs for Connection Diagnostics
        ffmpeg_command = request.data.get('ffmpeg_command', '')
        ffmpeg_stderr = request.data.get('ffmpeg_stderr', '')
        from django.core.cache import cache
        if ffmpeg_command or ffmpeg_stderr:
            cache.set(f"ffmpeg_diagnostics_{computer.id}", {
                "command": ffmpeg_command,
                "stderr": ffmpeg_stderr,
                "updated_at": timezone.now().isoformat()
            }, timeout=60)
            
        # Update computer fields
        computer.cpu_usage = cpu
        computer.ram_usage = ram
        computer.disk_usage = disk
        computer.network_speed = net_speed
        computer.uptime = uptime
        computer.last_seen = timezone.now()
        
        # If currently streaming, preserve streaming status; else mark online
        if computer.status != Computer.Statuses.STREAMING:
            computer.status = Computer.Statuses.ONLINE
            
        # Update resolution & FPS if streaming metrics are supplied
        if 'resolution' in request.data:
            computer.current_resolution = request.data.get('resolution')
        if 'fps' in request.data:
            computer.current_fps = int(request.data.get('fps', 0))
        if 'bitrate' in request.data:
            computer.current_bitrate = float(request.data.get('bitrate', 0.0))
            
        # Update client IP address dynamically
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        computer.ip_address = x_forwarded_for.split(',')[0].strip() if x_forwarded_for else request.META.get('REMOTE_ADDR')
        
        computer.save()
        
        # Log heartbeat record
        Heartbeat.objects.create(
            computer=computer,
            cpu_usage=cpu,
            ram_usage=ram,
            disk_usage=disk,
            network_speed=net_speed,
            uptime=uptime
        )
        
        return Response({'status': 'ok'})


class AgentStartStreamAPIView(APIView):
    """
    POST /api/screens/start/
    Notifies that desktop streaming has commenced.
    """
    permission_classes = [permissions.AllowAny]

    def post(self, request):
        computer = get_authenticated_agent(request)
        if not computer:
            return Response({'detail': _('Invalid agent token.')}, status=status.HTTP_401_UNAUTHORIZED)
            
        # Set state
        computer.status = Computer.Statuses.STREAMING
        computer.last_seen = timezone.now()
        
        resolution = request.data.get('resolution', '1920x1080')
        fps = int(request.data.get('fps', 30))
        bitrate = float(request.data.get('bitrate', 2000))
        
        computer.current_resolution = resolution
        computer.current_fps = fps
        computer.current_bitrate = bitrate
        computer.save()
        
        # Close any previous orphaned sessions first
        ScreenSession.objects.filter(computer=computer, is_active=True).update(
            is_active=False, 
            ended_at=timezone.now()
        )
        
        # Open new session
        ScreenSession.objects.create(
            computer=computer,
            resolution=resolution,
            fps=fps,
            bitrate=bitrate,
            is_active=True
        )
        
        ActivityLog.objects.create(
            user=None,
            action='agent_stream_started',
            description=f"Desktop streaming started on computer '{computer.name}' (Asset: {computer.asset_number}).",
            ip_address=computer.ip_address
        )
        
        return Response({'status': 'ok'})


class AgentStopStreamAPIView(APIView):
    """
    POST /api/screens/stop/
    Notifies that desktop streaming has stopped.
    """
    permission_classes = [permissions.AllowAny]

    def post(self, request):
        computer = get_authenticated_agent(request)
        if not computer:
            return Response({'detail': _('Invalid agent token.')}, status=status.HTTP_401_UNAUTHORIZED)
            
        computer.status = Computer.Statuses.ONLINE
        computer.last_seen = timezone.now()
        computer.save()
        
        # Terminate active sessions
        sessions = ScreenSession.objects.filter(computer=computer, is_active=True)
        for s in sessions:
            s.is_active = False
            s.ended_at = timezone.now()
            s.save()
            
        ActivityLog.objects.create(
            user=None,
            action='agent_stream_stopped',
            description=f"Desktop streaming stopped on computer '{computer.name}' (Asset: {computer.asset_number}).",
            ip_address=computer.ip_address
        )
        
        return Response({'status': 'ok'})


class ScreenSnapshotAPIView(APIView):
    """
    POST /api/screens/snapshot/
    Receives screenshots uploaded by either the browser client (admin taking snapshots) 
    or the desktop agents themselves.
    """
    def post(self, request):
        screenshot_file = request.FILES.get('screenshot')
        computer_id = request.data.get('computer')
        
        if not screenshot_file or not computer_id:
            return Response(
                {'detail': _('File screenshot and parameter computer are required.')},
                status=status.HTTP_400_BAD_REQUEST
            )
            
        # Locate computer (depends on authentication)
        computer = None
        if request.user.is_authenticated:
            # Browser client
            if request.user.is_super_admin():
                computer = get_object_or_404(Computer, id=computer_id)
            else:
                computer = get_object_or_404(Computer, id=computer_id, region=request.user.region)
        else:
            # Check if agent token is supplied in headers
            computer = get_authenticated_agent(request)
            if not computer or str(computer.id) != str(computer_id):
                return Response(
                    {'detail': _('Authentication failed or invalid computer scope.')},
                    status=status.HTTP_401_UNAUTHORIZED
                )
                
        # Save snapshot
        snapshot = ScreenSnapshot.objects.create(
            screenshot=screenshot_file,
            computer=computer,
            region=computer.region,
            captured_by=request.user if request.user.is_authenticated else None
        )
        
        operator_name = request.user.username if request.user.is_authenticated else "Agent"
        ActivityLog.objects.create(
            user=request.user if request.user.is_authenticated else None,
            action='screenshot_captured',
            description=f"Desktop screenshot captured for computer '{computer.name}' by {operator_name}.",
            ip_address=request.META.get('REMOTE_ADDR')
        )
        
        return Response({
            'status': 'success',
            'snapshot_id': snapshot.id,
            'screenshot_url': snapshot.screenshot.url
        })


class ComputerViewSet(viewsets.ModelViewSet):
    """
    API endpoint listing and editing registered computers.
    """
    serializer_class = ComputerSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.is_super_admin():
            return Computer.objects.all()
        elif user.is_region_admin() and hasattr(user, 'region'):
            return Computer.objects.filter(region=user.region)
        return Computer.objects.none()
        
    def perform_create(self, serializer):
        user = self.request.user
        if user.is_region_admin():
            serializer.save(region=user.region)
        else:
            serializer.save()
