# Generated by Django 5.2.16 on 2026-07-31 17:19

import django.db.models.deletion
import django.utils.timezone
import recordings.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('regions', '0001_initial'),
        ('sources', '0004_alter_streamingsetting_turn_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.IntegerField(default=30, verbose_name='Retention Days')),
                ('auto_cleanup_enabled', models.BooleanField(default=True, verbose_name='Auto Cleanup Enabled')),
                ('max_storage_gb', models.IntegerField(default=500, verbose_name='Max Storage Quota (GB)')),
                ('max_duration_hours', models.IntegerField(default=24, verbose_name='Max Recording Duration (Hours)')),
                ('auto_delete_policy', models.CharField(choices=[('oldest_first', 'Delete Oldest First'), ('warn_only', 'Send Warning Only'), ('none', 'Disabled')], default='oldest_first', max_length=30, verbose_name='Auto Delete Policy')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Storage Policy',
                'verbose_name_plural': 'Storage Policies',
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stream_id', models.CharField(db_index=True, max_length=100, verbose_name='Stream ID')),
                ('title', models.CharField(default='Live Stream', max_length=255, verbose_name='Stream Title')),
                ('status', models.CharField(choices=[('live', 'Live Streaming'), ('ended', 'Ended'), ('error', 'Stream Error')], default='live', max_length=20, verbose_name='Status')),
                ('peak_viewers', models.IntegerField(default=0, verbose_name='Peak Viewers')),
                ('current_viewers', models.IntegerField(default=0, verbose_name='Current Viewers')),
                ('total_views', models.IntegerField(default=0, verbose_name='Total Views')),
                ('resolution', models.CharField(default='1920x1080', max_length=20, verbose_name='Resolution')),
                ('fps', models.IntegerField(default=30, verbose_name='FPS')),
                ('avg_bitrate_kbps', models.IntegerField(default=2500, verbose_name='Avg Bitrate (Kbps)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='cameras.camera', verbose_name='Camera')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='regions.region', verbose_name='Region')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='sources.livesource', verbose_name='Live Source')),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Live Stream Recording', max_length=255, verbose_name='Recording Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='File Path')),
                ('file_url', models.CharField(blank=True, max_length=500, verbose_name='File URL')),
                ('filesize_bytes', models.BigIntegerField(default=0, verbose_name='Filesize (bytes)')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Duration (seconds)')),
                ('resolution', models.CharField(default='1080p', max_length=20, verbose_name='Resolution')),
                ('fps', models.IntegerField(default=30, verbose_name='FPS')),
                ('bitrate_kbps', models.IntegerField(default=2500, verbose_name='Bitrate (Kbps)')),
                ('codec', models.CharField(default='h264/aac', max_length=50, verbose_name='Codec')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=recordings.models.recording_thumbnail_path, verbose_name='Thumbnail')),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('completed', 'Completed'), ('processing', 'Processing'), ('failed', 'Failed'), ('archived', 'Archived')], default='recording', max_length=20, verbose_name='Status')),
                ('retention_policy', models.CharField(choices=[('never', 'Never Delete'), ('7_days', 'Delete after 7 days'), ('14_days', 'Delete after 14 days'), ('30_days', 'Delete after 30 days')], default='never', max_length=20, verbose_name='Retention Policy')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_sessions', to='cameras.camera', verbose_name='Camera')),
                ('live_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_session', to='recordings.livesession', verbose_name='Live Session')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_sessions', to='regions.region', verbose_name='Region')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_sessions', to='sources.livesource', verbose_name='Live Source')),
            ],
            options={
                'verbose_name': 'Recording Session',
                'verbose_name_plural': 'Recording Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityRendition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20, verbose_name='Quality Label')),
                ('height', models.IntegerField(default=720, verbose_name='Height (px)')),
                ('width', models.IntegerField(default=1280, verbose_name='Width (px)')),
                ('bitrate_kbps', models.IntegerField(default=2500, verbose_name='Bitrate (Kbps)')),
                ('playlist_url', models.CharField(max_length=500, verbose_name='Playlist URL')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('live_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='recordings.livesession', verbose_name='Live Session')),
                ('recording_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='recordings.recordingsession', verbose_name='Recording Session')),
            ],
            options={
                'verbose_name': 'Quality Rendition',
                'verbose_name_plural': 'Quality Renditions',
                'ordering': ['-height'],
            },
        ),
        migrations.CreateModel(
            name='ViewerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('join', 'Viewer Joined'), ('leave', 'Viewer Left'), ('heartbeat', 'Heartbeat'), ('seek', 'Playback Seek'), ('quality_change', 'Quality Change')], default='join', max_length=20, verbose_name='Event Type')),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Viewer IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_events', to='recordings.livesession', verbose_name='Live Session')),
            ],
            options={
                'verbose_name': 'Viewer Event',
                'verbose_name_plural': 'Viewer Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
