# Generated by Django 5.2.16 on 2026-07-13 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Computer Name')),
                ('asset_number', models.CharField(max_length=100, unique=True, verbose_name='Asset Number')),
                ('os', models.CharField(max_length=100, verbose_name='Operating System')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('building', models.CharField(max_length=100, verbose_name='Building')),
                ('floor', models.CharField(max_length=50, verbose_name='Floor')),
                ('room', models.CharField(max_length=50, verbose_name='Room')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('agent_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Agent ID')),
                ('agent_secret_key', models.CharField(blank=True, max_length=256, verbose_name='Agent Secret Key')),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('streaming', 'Streaming'), ('disconnected', 'Disconnected')], default='offline', max_length=20, verbose_name='Status')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('current_resolution', models.CharField(blank=True, max_length=50, verbose_name='Current Resolution')),
                ('current_fps', models.IntegerField(default=0, verbose_name='Current FPS')),
                ('current_bitrate', models.FloatField(default=0.0, verbose_name='Current Bitrate (Kbps)')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='Hostname')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('os_version', models.CharField(blank=True, max_length=150, verbose_name='OS Version')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('mac_address', models.CharField(blank=True, max_length=50, verbose_name='MAC Address')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='CPU Usage (%)')),
                ('ram_usage', models.FloatField(default=0.0, verbose_name='RAM Usage (%)')),
                ('disk_usage', models.FloatField(default=0.0, verbose_name='Disk Usage (%)')),
                ('network_speed', models.FloatField(default=0.0, verbose_name='Network Speed (Mbps)')),
                ('uptime', models.FloatField(default=0.0, verbose_name='Uptime (Hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='regions.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
                'ordering': ['region', 'building', 'room', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('computer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='screens.computer', verbose_name='Computer')),
            ],
            options={
                'verbose_name': 'Agent Token',
                'verbose_name_plural': 'Agent Tokens',
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(verbose_name='CPU Usage (%)')),
                ('ram_usage', models.FloatField(verbose_name='RAM Usage (%)')),
                ('disk_usage', models.FloatField(verbose_name='Disk Usage (%)')),
                ('network_speed', models.FloatField(verbose_name='Network Speed (Mbps)')),
                ('uptime', models.FloatField(verbose_name='Uptime (Hours)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='screens.computer', verbose_name='Computer')),
            ],
            options={
                'verbose_name': 'Heartbeat',
                'verbose_name_plural': 'Heartbeats',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScreenSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=50, verbose_name='Resolution')),
                ('fps', models.IntegerField(verbose_name='FPS')),
                ('bitrate', models.FloatField(verbose_name='Bitrate (Kbps)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_sessions', to='screens.computer', verbose_name='Computer')),
            ],
            options={
                'verbose_name': 'Screen Session',
                'verbose_name_plural': 'Screen Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='screenshots/', verbose_name='Screenshot')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='Captured At')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Captured By')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='screens.computer', verbose_name='Computer')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_snapshots', to='regions.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Screen Snapshot',
                'verbose_name_plural': 'Screen Snapshots',
                'ordering': ['-captured_at'],
            },
        ),
    ]
