# Generated by Django 5.2.16 on 2026-07-13 19:55

import django.db.models.deletion
import sources.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Source Name')),
                ('source_type', models.CharField(choices=[('IP_CAMERA', 'IP Camera'), ('SCREEN_SHARE', 'Desktop Screen'), ('WEB_BROWSER', 'Browser Tab'), ('WEBCAM', 'Webcam')], max_length=20, verbose_name='Source Type')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('online', 'Online'), ('recording', 'Recording'), ('offline', 'Offline')], default='idle', max_length=20, verbose_name='Status')),
                ('recording_enabled', models.BooleanField(default=False, verbose_name='Recording Enabled')),
                ('streaming_url', models.CharField(blank=True, max_length=500, verbose_name='Streaming URL')),
                ('rtsp_url', models.CharField(blank=True, max_length=500, verbose_name='RTSP URL')),
                ('rtsp_username', models.CharField(blank=True, max_length=100, verbose_name='RTSP Username')),
                ('rtsp_password', models.CharField(blank=True, max_length=100, verbose_name='RTSP Password')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Building')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='Floor')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Room')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_connected', models.DateTimeField(blank=True, null=True, verbose_name='Last Connected')),
                ('last_disconnected', models.DateTimeField(blank=True, null=True, verbose_name='Last Disconnected')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sources', to='regions.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Live Source',
                'verbose_name_plural': 'Live Sources',
                'ordering': ['region', 'source_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=sources.models.recording_upload_path, verbose_name='Recording File')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration (seconds)')),
                ('filesize', models.BigIntegerField(default=0, verbose_name='Filesize (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('live_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='sources.livesource', verbose_name='Live Source')),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
                'ordering': ['-created_at'],
            },
        ),
    ]
