# Generated by Django 5.2.16 on 2026-07-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Node Name')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='CPU Usage (%)')),
                ('ram_usage', models.FloatField(default=0.0, verbose_name='RAM Usage (%)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('priority', models.IntegerField(default=1, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Streaming Node',
                'verbose_name_plural': 'Streaming Nodes',
                'ordering': ['priority', '-cpu_usage'],
            },
        ),
        migrations.CreateModel(
            name='StreamingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediamtx_url', models.CharField(default='http://127.0.0.1:9997', max_length=255, verbose_name='MediaMTX API URL')),
                ('mediamtx_webrtc_url', models.CharField(default='http://127.0.0.1:8889', max_length=255, verbose_name='MediaMTX WebRTC URL')),
                ('mediamtx_hls_url', models.CharField(default='http://127.0.0.1:8888', max_length=255, verbose_name='MediaMTX HLS URL')),
                ('turn_url', models.CharField(default='turn:live.akhu.uz:3478?transport=udp', max_length=255, verbose_name='TURN Server URL')),
                ('stun_url', models.CharField(default='stun:stun.l.google.com:19302', max_length=255, verbose_name='STUN Server URL')),
                ('domain', models.CharField(default='live.akhu.uz', max_length=100, verbose_name='Production Domain')),
                ('https_enabled', models.BooleanField(default=True, verbose_name='HTTPS Enabled')),
                ('recording_enabled', models.BooleanField(default=True, verbose_name='Recording Enabled')),
            ],
            options={
                'verbose_name': 'Streaming Setting',
                'verbose_name_plural': 'Streaming Settings',
            },
        ),
    ]
