# Generated by Django 5.2.16 on 2026-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_streamingsetting_dvr_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingsetting',
            name='turn_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='TURN Server URL'),
        ),
    ]
