# Generated by Django 5.2.16 on 2026-08-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_alter_streamingsetting_turn_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesource',
            name='recording_enabled',
        ),
        migrations.RemoveField(
            model_name='streamingsetting',
            name='dvr_buffer_minutes',
        ),
        migrations.RemoveField(
            model_name='streamingsetting',
            name='mediamtx_playback_url',
        ),
        migrations.RemoveField(
            model_name='streamingsetting',
            name='recording_enabled',
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
