# Generated by Django 5.2.16 on 2026-07-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('started', 'Stream Started'), ('stopped', 'Stream Stopped')], max_length=20, verbose_name='Action')),
                ('bandwidth', models.FloatField(blank=True, null=True, verbose_name='Bandwidth (Mbps)')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_logs', to='cameras.camera', verbose_name='Camera')),
            ],
            options={
                'verbose_name': 'Streaming Log',
                'verbose_name_plural': 'Streaming Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
